from datetime import timedelta

DOMAIN = "microaqua"
DEFAULT_PORT = 7963
DEFAULT_PAYLOAD = "TCPSCP?"
DEFAULT_TIMEOUT = 2
DEFAULT_UPDATE_INTERVAL = 1
DEFAULT_DATA_VALID_SECONDS = 5
DEFAULT_SCAN_INTERVAL = timedelta(seconds=DEFAULT_UPDATE_INTERVAL)
DEFAULT_NAME = "microAQUA"
