- id: 'microAQUA_1_not_resp'
  alias: Brak komunikacji z microAQUA nr.1
  trigger:
  - platform: state
    entity_id: sensor.uaqua_1
    for: 00:05:00
  action:
  - service: notify.persistent_notification
    data:
      title: microAQUA nr.1 nie odpowiada
      message: Brak aktualnych pomiarow z urzadzenia microAQUA nr.1
  
- id: 'microAQUA_1_no_valid_data'
  alias: Brak aktualnych danych z microAQUA nr.1
  trigger:
  - platform: state
    entity_id: sensor.uaqua_1
    for: 00:00:15
  action:
  - service: homeassistant.update_entity
    target:
      entity_id:
      - sensor.uaqua_1_last_update
      - sensor.uaqua_1_ph
      - sensor.uaqua_1_temp1
      - sensor.uaqua_1_temp2
      - sensor.uaqua_1_temp3
      - sensor.uaqua_1_temp4
      - sensor.uaqua_1_co2_socket
      - sensor.uaqua_1_o2_socket
      - sensor.uaqua_1_termoreg_socket
      - sensor.uaqua_1_fan_controller
      - sensor.uaqua_1_led_1
      - sensor.uaqua_1_led_2
      - sensor.uaqua_1_led_3
      - sensor.uaqua_1_led_4
      - sensor.uaqua_1_alarmy_temp
      - sensor.uaqua_1_alarmy_ph
      - sensor.uaqua_1_alarm_akustyczny
      - sensor.uaqua_1_temp_alarm_min_value
      - sensor.uaqua_1_temp_alarm_max_value
      - sensor.uaqua_1_ph_alarm_min_value
      - sensor.uaqua_1_ph_alarm_max_value
      - sensor.uaqua_1_no_reg_time
      - sensor.uaqua_1
  mode: single

#---------------------------------------------------#
#           microAQUA 2'nd DEVICE SECTION           #
#---------------------------------------------------#
#                                                   #
#     uncomment code in this section to add 2'nd    #
#           microAQUA device to the system          #
#                                                   #
#       To do this ,select configuration code       #
#       in this section and press 'Ctrl' + '/'      #
#---------------------------------------------------#
# - id: 'microAQUA_2_not_resp'
#   alias: Brak komunikacji z microAQUA nr.2
#   trigger:
#   - platform: state
#     entity_id: sensor.uaqua_2
#     for: 00:05:00
#   action:
#   - service: notify.persistent_notification
#     data:
#       title: microAQUA nr.2 nie odpowiada
#       message: Brak aktualnych pomiarow z urzadzenia microAQUA nr.2
# - id: 'microAQUA_2_no_valid_data'
#   alias: Brak aktualnych danych z microAQUA nr.2
#   trigger:
#   - platform: state
#     entity_id: sensor.uaqua_2
#     for: 00:00:15
#   action:
#   - service: homeassistant.update_entity
#     target:
#       entity_id:
#       - sensor.uaqua_2_last_update
#       - sensor.uaqua_2_ph
#       - sensor.uaqua_2_temp1
#       - sensor.uaqua_2_temp2
#       - sensor.uaqua_2_temp3
#       - sensor.uaqua_2_temp4
#       - sensor.uaqua_2_co2_socket
#       - sensor.uaqua_2_o2_socket
#       - sensor.uaqua_2_termoreg_socket
#       - sensor.uaqua_2_fan_controller
#       - sensor.uaqua_2_led_1
#       - sensor.uaqua_2_led_2
#       - sensor.uaqua_2_led_3
#       - sensor.uaqua_2_led_4
#       - sensor.uaqua_2_alarmy_temp
#       - sensor.uaqua_2_alarmy_ph
#       - sensor.uaqua_2_alarm_akustyczny
#       - sensor.uaqua_2_temp_alarm_min_value
#       - sensor.uaqua_2_temp_alarm_max_value
#       - sensor.uaqua_2_ph_alarm_min_value
#       - sensor.uaqua_2_ph_alarm_max_value
#       - sensor.uaqua_2_no_reg_time
#       - sensor.uaqua_2
#   mode: single
#---------------------------------------------------#
#        END microAQUA 2'nd DEVICE SECTION          #
#---------------------------------------------------#
 
#---------------------------------------------------#
#           microAQUA 3'rd DEVICE SECTION           #
#---------------------------------------------------#
#                                                   #
#     uncomment code in this section to add 3'rd    #
#           microAQUA device to the system          #
#                                                   #
#       To do this ,select configuration code       #
#       in this section and press 'Ctrl' + '/'      #
#---------------------------------------------------#
# - id: microAQUA_3_not_resp
#   alias: Brak komunikacji z microAQUA nr.3
#   trigger:
#   - platform: state
#     entity_id: sensor.uaqua_3
#     for: 00:05:00
#   action:
#   - service: notify.persistent_notification
#     data:
#       title: microAQUA nr.3 nie odpowiada
#       message: Brak aktualnych pomiarow z urzadzenia microAQUA nr.3
#   mode: single
# - id: 'microAQUA_3_no_valid_data'
#   alias: Brak aktualnych danych z microAQUA nr.3
#   trigger:
#   - platform: state
#     entity_id: sensor.uaqua_3
#     for: 00:00:15
#   action:
#   - service: homeassistant.update_entity
#     target:
#       entity_id:
#       - sensor.uaqua_3_last_update
#       - sensor.uaqua_3_ph
#       - sensor.uaqua_3_temp1
#       - sensor.uaqua_3_temp2
#       - sensor.uaqua_3_temp3
#       - sensor.uaqua_3_temp4
#       - sensor.uaqua_3_co2_socket
#       - sensor.uaqua_3_o2_socket
#       - sensor.uaqua_3_termoreg_socket
#       - sensor.uaqua_3_fan_controller
#       - sensor.uaqua_3_led_1
#       - sensor.uaqua_3_led_2
#       - sensor.uaqua_3_led_3
#       - sensor.uaqua_3_led_4
#       - sensor.uaqua_3_alarmy_temp
#       - sensor.uaqua_3_alarmy_ph
#       - sensor.uaqua_3_alarm_akustyczny
#       - sensor.uaqua_3_temp_alarm_min_value
#       - sensor.uaqua_3_temp_alarm_max_value
#       - sensor.uaqua_3_ph_alarm_min_value
#       - sensor.uaqua_3_ph_alarm_max_value
#       - sensor.uaqua_3_no_reg_time
#       - sensor.uaqua_3
#   mode: single
#---------------------------------------------------#
#        END microAQUA 3'rd DEVICE SECTION          #
#---------------------------------------------------#
