- platform: template
  switches:
    uaqua_1_no_reg_time_by_slider:
      friendly_name: Regulacja ON/OFF
      icon_template: >
        {% if (states('sensor.uaqua_1')!= 'unknown') %}
          {% if ((states('sensor.uaqua_1').split(';')[17]) == '0') %}
            hass:power-plug
          {% else %}
            hass:power-plug-off
          {% endif %}
        {% else %}
          hass:power-plug-off
        {% endif %}
      value_template: "{{ not((states('sensor.uaqua_1').split(';')[17]) == '0') }}"
      turn_on: 
        - service: shell_command.uaqua_1_no_reg_on_cmd
          data:
            IP: !secret microAQUA_1_IP
            port: !secret microAQUA_1_port #
#------------------------------------------------------------------
#   Uncomment if you want to reset slider after setting the value
#------------------------------------------------------------------
#       - service: input_number.set_value
#         target: 
#           entity_id: input_number.uaqua_1_set_no_reg_time
#         data :
#           value: 0
#------------------------------------------------------------------
      turn_off:
        service: shell_command.no_reg_off_cmd
        data:
          IP: !secret microAQUA_1_IP
          port: !secret microAQUA_1_port 
    uaqua_1_disarm_sound_alarm:
      value_template: "{{(not(((states('sensor.uaqua_1').split(';')[18]) |int |bitwise_and(128))==128)) and(((states('sensor.uaqua_1').split(';')[18]) |int |bitwise_and(127))!=0) }}"
      friendly_name: Wyłącz Alarm Dźwiękowy
      icon_template: >
        {% if (states('sensor.uaqua_1')!= 'unknown') %}
          {% if (((states('sensor.uaqua_1').split(';')[18]) |int |bitwise_and(127))!=0) %}
            {% if (((states('sensor.uaqua_1').split(';')[18]) |int |bitwise_and(128))==128) %}
              hass:volume-off
            {% else %}
              hass:volume-high
            {% endif %}    
          {% else %}
            hass:volume-off
          {% endif %}
        {% else %}
          hass:volume-off
        {% endif %}
      turn_on: 
      turn_off:
        service: shell_command.disarm_sound_alarm_cmd
        data:
          IP: !secret microAQUA_1_IP
          port: !secret microAQUA_1_port

#---------------------------------------------------#
#           microAQUA 2'nd DEVICE SECTION           #
#---------------------------------------------------#
#                                                   #
#     uncomment code in this section to add 2'nd    #
#           microAQUA device to the system          #
#                                                   #
#       To do this ,select configuration code       #
#       in this section and press 'Ctrl' + '/'      #
#---------------------------------------------------#
#     uaqua_2_no_reg_time_by_slider:
#       friendly_name: Regulacja ON/OFF
#       icon_template: >
#         {% if (states('sensor.uaqua_2')!= 'unknown') %}
#           {% if ((states('sensor.uaqua_2').split(';')[17]) == '0') %}
#             hass:power-plug
#           {% else %}
#             hass:power-plug-off
#           {% endif %}
#         {% else %}
#           hass:power-plug-off
#         {% endif %}
#       value_template: "{{ not((states('sensor.uaqua_2').split(';')[17]) == '0') }}"
#       turn_on: 
#         - service: shell_command.uaqua_2_no_reg_on_cmd
#           data:
#             IP: !secret microAQUA_2_IP
#             port: !secret microAQUA_2_port
#------------------------------------------------------------------
#   Uncomment if you want to reset slider after setting the value
#------------------------------------------------------------------
#         - service: input_number.set_value
#           target: 
#             entity_id: input_number.uaqua_2_set_no_reg_time
#           data :
#             value: 0
#------------------------------------------------------------------
#       turn_off:
#         service: shell_command.no_reg_off_cmd
#         data:
#           IP: !secret microAQUA_2_IP
#           port: !secret microAQUA_2_port
          

#     uaqua_2_disarm_sound_alarm:
#       value_template: "{{(not(((states('sensor.uaqua_2').split(';')[18]) |int |bitwise_and(128))==128)) and(((states('sensor.uaqua_2').split(';')[18]) |int |bitwise_and(127))!=0) }}"
#       friendly_name: Wyłącz Alarm Dźwiękowy
#       icon_template: >
#         {% if (states('sensor.uaqua_2')!= 'unknown') %}
#           {% if (((states('sensor.uaqua_2').split(';')[18]) |int |bitwise_and(127))!=0) %}
#             {% if (((states('sensor.uaqua_2').split(';')[18]) |int |bitwise_and(128))==128) %}
#               hass:volume-off
#             {% else %}
#               hass:volume-high
#             {% endif %}    
#           {% else %}
#             hass:volume-off
#           {% endif %}
#         {% else %}
#           hass:volume-off
#         {% endif %}
#       turn_on: 
#       turn_off:
#         service: shell_command.disarm_sound_alarm_cmd
#         data:
#           IP: !secret microAQUA_2_IP
#           port: !secret microAQUA_2_port
#---------------------------------------------------#
#        END microAQUA 2'nd DEVICE SECTION          #
#---------------------------------------------------#


#---------------------------------------------------#
#           microAQUA 3'rd DEVICE SECTION           #
#---------------------------------------------------#
#                                                   #
#     uncomment code in this section to add 3'rd    #
#           microAQUA device to the system          #
#                                                   #
#       To do this ,select configuration code       #
#       in this section and press 'Ctrl' + '/'      #
#---------------------------------------------------#
    # uaqua_3_no_reg_time_by_slider:
    #   friendly_name: Regulacja ON/OFF
    #   icon_template: >
    #     {% if (states('sensor.uaqua_3')!= 'unknown') %}
    #       {% if ((states('sensor.uaqua_3').split(';')[17]) == '0') %}
    #         hass:power-plug
    #       {% else %}
    #         hass:power-plug-off
    #       {% endif %}
    #     {% else %}
    #       hass:power-plug-off
    #     {% endif %}
    #   value_template: "{{ not((states('sensor.uaqua_3').split(';')[17]) == '0') }}"
    #   turn_on: 
    #     - service: shell_command.uaqua_3_no_reg_on_cmd
    #       data:
    #         IP: !secret microAQUA_3_IP
    #         port: !secret microAQUA_3_port
#------------------------------------------------------------------
#   Uncomment if you want to reset slider after setting the value
#------------------------------------------------------------------
#     - service: input_number.set_value
#       target: 
#         entity_id: input_number.uaqua_3_set_no_reg_time
#       data :
#         value: 0
#------------------------------------------------------------------
    #   turn_off:
    #     service: shell_command.no_reg_off_cmd
    #     data:
    #       IP: !secret microAQUA_3_IP
    #       port: !secret microAQUA_3_port

    # uaqua_3_disarm_sound_alarm:
    #   value_template: "{{(not(((states('sensor.uaqua_3').split(';')[18]) |int |bitwise_and(128))==128)) and(((states('sensor.uaqua_3').split(';')[18]) |int |bitwise_and(127))!=0) }}"
    #   friendly_name: Wyłącz Alarm Dźwiękowy
    #   icon_template: >
    #     {% if (states('sensor.uaqua_3')!= 'unknown') %}
    #       {% if (((states('sensor.uaqua_3').split(';')[18]) |int |bitwise_and(127))!=0) %}
    #         {% if (((states('sensor.uaqua_3').split(';')[18]) |int |bitwise_and(128))==128) %}
    #           hass:volume-off
    #         {% else %}
    #           hass:volume-high
    #         {% endif %}    
    #       {% else %}
    #         hass:volume-off
    #       {% endif %}
    #     {% else %}
    #       hass:volume-off
    #     {% endif %}
    #   turn_on: 
    #   turn_off:
    #     service: shell_command.disarm_sound_alarm_cmd
    #     data:
    #       IP: !secret microAQUA_3_IP
    #       port: !secret microAQUA_3_port
#---------------------------------------------------#
#        END microAQUA 3'rd DEVICE SECTION          #
#---------------------------------------------------#
